// Generated by Classiq.
// Classiq version: 0.29.1
// Creation timestamp: 2023-10-01T06:14:38.989625+00:00
// Random seed: 1027785478

OPENQASM 2.0;
include "qelib1.inc";
qreg q[28];
x q[0];
cx q[0],q[1];
cx q[1],q[2];
cx q[1],q[3];
cx q[1],q[4];
cx q[0],q[5];
cx q[0],q[6];
cx q[0],q[3];
cx q[0],q[4];
x q[7];
cx q[7],q[8];
cx q[7],q[9];
cx q[7],q[10];
cx q[7],q[11];
cx q[8],q[11];
cx q[7],q[12];
cx q[8],q[12];
cx q[8],q[13];
x q[14];
cx q[14],q[5];
cx q[14],q[6];
cx q[6],q[15];
cx q[6],q[16];
cx q[14],q[17];
cx q[14],q[18];
cx q[14],q[15];
cx q[14],q[19];
cx q[5],q[2];
cx q[5],q[20];
cx q[17],q[20];
cx q[17],q[18];
cx q[17],q[19];
cx q[17],q[16];
x q[21];
cx q[21],q[9];
cx q[21],q[22];
cx q[22],q[23];
cx q[22],q[24];
cx q[9],q[11];
cx q[7],q[25];
cx q[9],q[25];
cx q[21],q[10];
cx q[10],q[25];
cx q[7],q[18];
cx q[21],q[18];
cx q[10],q[18];
cx q[21],q[23];
cx q[21],q[26];
cx q[10],q[26];
cx q[10],q[24];
